# Generated by Django 4.2.29 on 2026-04-16 09:32

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='avatars/', validators=[apps.core.validators.validate_image_upload], verbose_name='头像'),
        ),
    ]
