# Generated by Django 4.2.29 on 2026-04-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='site_author',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='网站作者'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='site_icp',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='ICP备案号'),
        ),
    ]
