# Generated by Django 4.2.29 on 2026-04-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_siteconfig_site_author_siteconfig_site_icp"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="site_gongan_beian",
            field=models.CharField(blank=True, default="", max_length=128, verbose_name="公安联网备案号"),
        ),
    ]
