# Generated by Django 4.2.29 on 2026-04-16 09:32

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteconfig_site_gongan_beian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='logo',
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to='logos/',
                validators=[apps.core.validators.validate_image_upload],
                verbose_name='网站Logo',
            ),
        ),
    ]
