# Generated by Django 5.1.6 on 2026-03-07 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="review_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="review_status",
            field=models.CharField(
                choices=[("pending", "待审核"), ("approved", "已通过"), ("rejected", "已拒绝")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="allow_comments",
            field=models.BooleanField(default=True, verbose_name="允许评论"),
        ),
    ]
