# Generated by Django 4.2.29 on 2026-03-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_category_name_alter_comment_content_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["post", "-created_at"], name="blog_commen_post_id_0b6431_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["review_status"], name="blog_commen_review__6b87fe_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["user"], name="blog_commen_user_id_dd6a39_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["-created_at"], name="blog_commen_created_1f5393_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["author"], name="blog_post_author__038a48_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["slug"], name="blog_post_slug_cdb902_idx"),
        ),
    ]
