# Generated by Django 4.2 on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_comment_blog_commen_post_id_0b6431_idx_and_more"),
    ]

    operations = [
        # Post 列表/首页常用：status + published_at + created_at
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["status", "-published_at", "-created_at"],
                name="blog_post_route_list_idx",
            ),
        ),
        # Post 分类页常用：status + category + published_at
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["status", "category", "-published_at"],
                name="blog_post_cate_list_idx",
            ),
        ),
        # Comment 文章详情页常用：post + review_status + created_at
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["post", "review_status", "created_at"],
                name="blog_comment_route_idx",
            ),
        ),
    ]
