# Generated by Django 4.2.29 on 2026-05-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_remove_comment_blog_comment_route_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["status", "-published_at"], name="idx_post_status_pub"),
        ),
    ]
