# Generated by Django 4.2 on 2026-03-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0003_alter_moderationlog_action_moderationadmin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensitiveword",
            name="category",
            field=models.CharField(blank=True, max_length=50, verbose_name="分类"),
        ),
        migrations.AddField(
            model_name="sensitiveword",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AddField(
            model_name="sensitiveword",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
