# Generated by Django 4.2.29 on 2026-03-21 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("moderation", "0004_sensitiveword_category_sensitiveword_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserReputation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score", models.IntegerField(default=50, verbose_name="信誉分")),
                ("total_posts", models.IntegerField(default=0, verbose_name="总发帖数")),
                ("approved_count", models.IntegerField(default=0, verbose_name="通过数")),
                ("rejected_count", models.IntegerField(default=0, verbose_name="拒绝数")),
                ("report_count", models.IntegerField(default=0, verbose_name="被举报次数")),
                ("clean_days", models.IntegerField(default=0, verbose_name="连续无违规天数")),
                ("last_clean_check", models.DateField(auto_now_add=True, verbose_name="上次检查日期")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reputation",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户信誉",
                "verbose_name_plural": "用户信誉",
            },
        ),
        migrations.CreateModel(
            name="ReputationLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("score_change", "分数变化"),
                            ("level_change", "等级变化"),
                            ("bonus", "奖励"),
                            ("penalty", "惩罚"),
                            ("manual", "手动调整"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                ("old_score", models.IntegerField(verbose_name="原分数")),
                ("new_score", models.IntegerField(verbose_name="新分数")),
                ("delta", models.IntegerField(verbose_name="变化量")),
                ("reason", models.CharField(blank=True, max_length=200, verbose_name="原因")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "user_reputation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="moderation.userreputation",
                        verbose_name="用户信誉",
                    ),
                ),
            ],
            options={
                "verbose_name": "信誉日志",
                "verbose_name_plural": "信誉日志",
                "ordering": ["-created_at"],
            },
        ),
    ]
