# Generated by Django 4.2.29 on 2026-05-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0006_alter_moderationadmin_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userreputation",
            name="last_violation_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="最近违规时间"),
        ),
        migrations.AddIndex(
            model_name="moderationlog",
            index=models.Index(fields=["target_type", "target_id"], name="idx_log_target"),
        ),
        migrations.AddIndex(
            model_name="moderationlog",
            index=models.Index(fields=["action"], name="idx_log_action"),
        ),
        migrations.AddIndex(
            model_name="moderationlog",
            index=models.Index(fields=["operator"], name="idx_log_operator"),
        ),
        migrations.AddIndex(
            model_name="moderationreminder",
            index=models.Index(fields=["is_processed"], name="idx_reminder_processed"),
        ),
        migrations.AddIndex(
            model_name="reputationlog",
            index=models.Index(fields=["user_reputation", "-created_at"], name="idx_replog_user_time"),
        ),
        migrations.AddIndex(
            model_name="sensitiveword",
            index=models.Index(fields=["is_active"], name="idx_sw_active"),
        ),
        migrations.AddIndex(
            model_name="userreputation",
            index=models.Index(fields=["score"], name="idx_reputation_score"),
        ),
    ]
