# Generated by Django 4.2.29 on 2026-03-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0002_reply_review_note_reply_review_status_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="reply",
            index=models.Index(fields=["topic", "-created_at"], name="forum_reply_topic_i_93f395_idx"),
        ),
        migrations.AddIndex(
            model_name="reply",
            index=models.Index(fields=["author"], name="forum_reply_author__c07146_idx"),
        ),
        migrations.AddIndex(
            model_name="reply",
            index=models.Index(fields=["review_status"], name="forum_reply_review__5e12ba_idx"),
        ),
        migrations.AddIndex(
            model_name="reply",
            index=models.Index(fields=["-created_at"], name="forum_reply_created_6cc7c5_idx"),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(fields=["board", "-last_reply_at"], name="forum_topic_board_i_5a1b3f_idx"),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(fields=["author"], name="forum_topic_author__d52f05_idx"),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(fields=["review_status"], name="forum_topic_review__b15c59_idx"),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(fields=["is_pinned"], name="forum_topic_is_pinn_87b70e_idx"),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(fields=["-created_at"], name="forum_topic_created_60d8a9_idx"),
        ),
    ]
