# Generated by Django 4.2 on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0003_reply_forum_reply_topic_i_93f395_idx_and_more"),
    ]

    operations = [
        # Topic 列表页常用：board + review_status + is_pinned + last_reply_at + created_at
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["board", "review_status", "-is_pinned", "-last_reply_at", "-created_at"],
                name="forum_topic_route_list_idx",
            ),
        ),
        # Topic API 常用过滤：review_status + board + created_at
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["review_status", "board", "-created_at"],
                name="forum_topic_api_qs_idx",
            ),
        ),
        # Reply 详情页/接口常用：topic + review_status + is_deleted + created_at
        migrations.AddIndex(
            model_name="reply",
            index=models.Index(
                fields=["topic", "review_status", "is_deleted", "created_at"],
                name="forum_reply_route_idx",
            ),
        ),
    ]
